//-----------------------------------------------------------------------
// <copyright file="GlobalSuppressions.cs" company="The Phantom Coder">
//     Copyright The Phantom Coder. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Code Analysis results, point to "Suppress Message", and click 
// "In Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix", Scope = "type", Target = "Phantom.PubSub.RemoveMessageFromQueue`1", Justification = "Does not have incorrect surrix")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "Phantom.PubSub.AssemblyLocator`1.#GetAssemblies()", Justification = "part of design to allow static members for each specialization of generic class")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Dlls", Scope = "member", Target = "Phantom.PubSub.AssemblyLocator`1.#GetDlls()", Justification = "Spelling is correct")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Phantom.PubSub.IQueueProvider`1.#ProcessQueueAsBatch(System.Func`3<Phantom.PubSub.MessagePacket`1<!0>,System.String,System.Boolean>)", Justification = "Required by design")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Msmq", Scope = "type", Target = "Phantom.PubSub.MsmqQueueProvider`1", Justification = "Spelling is correct")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Phantom.PubSub.IPublishSubscribeChannel`1.#GetSubscriptions()", Justification = "Properties are not appropriate in this case")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2001:AvoidCallingProblematicMethods", MessageId = "System.Reflection.Assembly.LoadFrom", Scope = "member", Target = "Phantom.PubSub.AssemblyLocator`1.#GetSubscribersInBin()", Justification = "Method is not problematic")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Phantom.PubSub.Subscriber`1.#SubscribersForThisMessage", Justification = "Not available for this collection")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Esent", Scope = "type", Target = "Phantom.PubSub.EsentStoreProvider`1", Justification = "Spelling is correct")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Esent", Scope = "type", Target = "Phantom.PubSub.EsentConfig", Justification = "Spelling is correct")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Esent", Scope = "type", Target = "Phantom.PubSub.EsentInstanceService`1", Justification = "Spelling is correct")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1000:DoNotDeclareStaticMembersOnGenericTypes", Scope = "member", Target = "Phantom.PubSub.EsentInstanceService`1.#Service", Justification = "Required by design")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Esent", Scope = "member", Target = "Phantom.PubSub.EsentInstanceService`1.#EsentInstance", Justification = "Spelling is correct")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Esent", Scope = "member", Target = "Phantom.PubSub.EsentInstanceService`1.#SheduleDisposingOfEsent()", Justification = "Spelling is correct")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Esent", Scope = "member", Target = "Phantom.PubSub.EsentInstanceService`1.#DisposeOfEsentInstance()", Justification = "Spelling is correct")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Esent", Scope = "type", Target = "Phantom.PubSub.EsentStore`1", Justification = "Spelling is correct")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Esent", Scope = "member", Target = "Phantom.PubSub.EsentInstanceService`1.#ScheduleDisposingOfEsent()", Justification = "Spelling is correct")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Esent", Scope = "type", Target = "Phantom.PubSub.EsentDatabaseException", Justification = "Spelling is correct")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Phantom.PubSub.EsentStore`1.#AddMetadata(System.Nullable`1<System.Int32>,System.Collections.Generic.List`1<Phantom.PubSub.ISubscriberMetadata>)", Justification = "Required by design")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Immediatly", Scope = "member", Target = "Phantom.PubSub.EsentInstanceService`1.#DisposeOfEsentInstanceImmediatly()", Justification = "Spelling is correct")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Esent", Scope = "member", Target = "Phantom.PubSub.EsentInstanceService`1.#DisposeOfEsentInstanceImmediatly()", Justification = "Spelling is correct")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "dbid", Scope = "member", Target = "Phantom.PubSub.EsentStoreProvider`1.#dbid", Justification = "Spelling is correct")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Phantom.PubSub.EsentStoreProvider`1.#GetAllMessages()", Justification = "Spelling is correct")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Esent", Scope = "type", Target = "Phantom.PubSub.IEsentStore`1", Justification = "Spelling is correct")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "metadatas", Scope = "member", Target = "Phantom.PubSub.IEsentStore`1.#AddMetadata(System.Nullable`1<System.Int32>,System.Collections.Generic.List`1<Phantom.PubSub.ISubscriberMetadata>)", Justification = "Spelling is correct")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "metadatas", Scope = "member", Target = "Phantom.PubSub.IEsentStore`1.#DeleteMetadata(System.Collections.Generic.IEnumerable`1<Phantom.PubSub.ISubscriberMetadata>)", Justification = "Spelling is correct")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Phantom.PubSub.IEsentStore`1.#GetAllMessages()", Justification = "Properties are not appropriate in this case")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Phantom.PubSub.IEsentStore`1.#GetRecordCount()", Justification = "Properties are not appropriate in this case")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Phantom.PubSub.IStoreProvider`1.#GetMessageCount()", Justification = "Properties are not appropriate in this case")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Utils", Scope = "type", Target = "Phantom.PubSub.Utils", Justification = "Spelling is correct")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "esent", Scope = "member", Target = "Phantom.PubSub.Utils.#esentSwitch", Justification = "Spelling is correct")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "msmq", Scope = "member", Target = "Phantom.PubSub.Utils.#msmqSwitch", Justification = "Spelling is correct")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Phantom.PubSub.EsentStoreProvider`1.#GetAllMessages()", Justification = "Spelling is correct")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA2210:AssembliesShouldHaveValidStrongNames", Justification = "Not signin")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists", Scope = "member", Target = "Phantom.PubSub.EsentStore`1.#GetMetadata(System.Int32)", Justification = "Required by design")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Phantom.PubSub.IStoreProvider`1.#ProcessStoreAsBatch(System.Func`3<Phantom.PubSub.MessagePacket`1<!0>,System.String,System.Boolean>)", Justification = "Required by design")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Esent", Scope = "member", Target = "Phantom.PubSub.Utils.#EsentSwitch", Justification = "Spelling is correct")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Msmq", Scope = "member", Target = "Phantom.PubSub.Utils.#MsmqSwitch", Justification = "Spelling is correct")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Metadatas", Scope = "member", Target = "Phantom.PubSub.MessagePacket`1.#ReplaceMetadatas(System.Collections.Generic.IEnumerable`1<Phantom.PubSub.ISubscriberMetadata>)", Justification = "Spelling is correct")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Datas", Scope = "member", Target = "Phantom.PubSub.MessagePacket`1.#ReplaceMetadatas(System.Collections.Generic.IEnumerable`1<Phantom.PubSub.ISubscriberMetadata>)", Justification = "Spelling is correct")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Datas", Scope = "member", Target = "Phantom.PubSub.MessagePacket`1.#AddRange(System.Collections.Generic.IEnumerable`1<Phantom.PubSub.ISubscriberMetadata>)", Justification = "Spelling is correct")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Phantom.PubSub.Repository`1.#GetAllMessages()", Justification = "Properties are not appropriate in this case")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Phantom.PubSub.Repository`1.#GetRecordCount()", Justification = "Properties are not appropriate in this case")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Deserializer", Scope = "member", Target = "Phantom.PubSub.Serializer.#Deserializer`1(System.String)", Justification = "Spelling is correct")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "Phantom.PubSub.AutoConfig`1.#.cctor()", Justification = "Required by design")]
