//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Entities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PubSubEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PubSubEntities object using the connection string found in the 'PubSubEntities' section of the application configuration file.
        /// </summary>
        public PubSubEntities() : base("name=PubSubEntities", "PubSubEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PubSubEntities object.
        /// </summary>
        public PubSubEntities(string connectionString) : base(connectionString, "PubSubEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PubSubEntities object.
        /// </summary>
        public PubSubEntities(EntityConnection connection) : base(connection, "PubSubEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Message> Messages
        {
            get
            {
                if ((_Messages == null))
                {
                    _Messages = base.CreateObjectSet<Message>("Messages");
                }
                return _Messages;
            }
        }
        private ObjectSet<Message> _Messages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Message2> Message2
        {
            get
            {
                if ((_Message2 == null))
                {
                    _Message2 = base.CreateObjectSet<Message2>("Message2");
                }
                return _Message2;
            }
        }
        private ObjectSet<Message2> _Message2;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Message3> Message3
        {
            get
            {
                if ((_Message3 == null))
                {
                    _Message3 = base.CreateObjectSet<Message3>("Message3");
                }
                return _Message3;
            }
        }
        private ObjectSet<Message3> _Message3;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Message4> Message4
        {
            get
            {
                if ((_Message4 == null))
                {
                    _Message4 = base.CreateObjectSet<Message4>("Message4");
                }
                return _Message4;
            }
        }
        private ObjectSet<Message4> _Message4;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Message5> Message5
        {
            get
            {
                if ((_Message5 == null))
                {
                    _Message5 = base.CreateObjectSet<Message5>("Message5");
                }
                return _Message5;
            }
        }
        private ObjectSet<Message5> _Message5;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Messages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMessages(Message message)
        {
            base.AddObject("Messages", message);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Message2 EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMessage2(Message2 message2)
        {
            base.AddObject("Message2", message2);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Message3 EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMessage3(Message3 message3)
        {
            base.AddObject("Message3", message3);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Message4 EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMessage4(Message4 message4)
        {
            base.AddObject("Message4", message4);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Message5 EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMessage5(Message5 message5)
        {
            base.AddObject("Message5", message5);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PubSubModel", Name="Message")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Message : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Message object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="messageID">Initial value of the MessageID property.</param>
        /// <param name="subscriptionID">Initial value of the SubscriptionID property.</param>
        /// <param name="guid">Initial value of the Guid property.</param>
        /// <param name="messagePutTime">Initial value of the MessagePutTime property.</param>
        /// <param name="timestamp">Initial value of the Timestamp property.</param>
        /// <param name="batchNumber">Initial value of the BatchNumber property.</param>
        /// <param name="messageReadTime">Initial value of the MessageReadTime property.</param>
        public static Message CreateMessage(global::System.Int32 id, global::System.String name, global::System.String messageID, global::System.String subscriptionID, global::System.Guid guid, global::System.DateTime messagePutTime, global::System.Byte[] timestamp, global::System.Int32 batchNumber, global::System.DateTime messageReadTime)
        {
            Message message = new Message();
            message.ID = id;
            message.Name = name;
            message.MessageID = messageID;
            message.SubscriptionID = subscriptionID;
            message.Guid = guid;
            message.MessagePutTime = messagePutTime;
            message.Timestamp = timestamp;
            message.BatchNumber = batchNumber;
            message.MessageReadTime = messageReadTime;
            return message;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                OnIDChanging(value);
                ReportPropertyChanging("ID");
                _ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID");
                OnIDChanged();
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MessageID
        {
            get
            {
                return _MessageID;
            }
            set
            {
                OnMessageIDChanging(value);
                ReportPropertyChanging("MessageID");
                _MessageID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MessageID");
                OnMessageIDChanged();
            }
        }
        private global::System.String _MessageID;
        partial void OnMessageIDChanging(global::System.String value);
        partial void OnMessageIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SubscriptionID
        {
            get
            {
                return _SubscriptionID;
            }
            set
            {
                OnSubscriptionIDChanging(value);
                ReportPropertyChanging("SubscriptionID");
                _SubscriptionID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SubscriptionID");
                OnSubscriptionIDChanged();
            }
        }
        private global::System.String _SubscriptionID;
        partial void OnSubscriptionIDChanging(global::System.String value);
        partial void OnSubscriptionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Guid
        {
            get
            {
                return _Guid;
            }
            set
            {
                if (_Guid != value)
                {
                    OnGuidChanging(value);
                    ReportPropertyChanging("Guid");
                    _Guid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Guid");
                    OnGuidChanged();
                }
            }
        }
        private global::System.Guid _Guid;
        partial void OnGuidChanging(global::System.Guid value);
        partial void OnGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime MessagePutTime
        {
            get
            {
                return _MessagePutTime;
            }
            set
            {
                OnMessagePutTimeChanging(value);
                ReportPropertyChanging("MessagePutTime");
                _MessagePutTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MessagePutTime");
                OnMessagePutTimeChanged();
            }
        }
        private global::System.DateTime _MessagePutTime;
        partial void OnMessagePutTimeChanging(global::System.DateTime value);
        partial void OnMessagePutTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Timestamp
        {
            get
            {
                return StructuralObject.GetValidValue(_Timestamp);
            }
            set
            {
                OnTimestampChanging(value);
                ReportPropertyChanging("Timestamp");
                _Timestamp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Timestamp");
                OnTimestampChanged();
            }
        }
        private global::System.Byte[] _Timestamp;
        partial void OnTimestampChanging(global::System.Byte[] value);
        partial void OnTimestampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BatchNumber
        {
            get
            {
                return _BatchNumber;
            }
            set
            {
                OnBatchNumberChanging(value);
                ReportPropertyChanging("BatchNumber");
                _BatchNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BatchNumber");
                OnBatchNumberChanged();
            }
        }
        private global::System.Int32 _BatchNumber;
        partial void OnBatchNumberChanging(global::System.Int32 value);
        partial void OnBatchNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime MessageReadTime
        {
            get
            {
                return _MessageReadTime;
            }
            set
            {
                OnMessageReadTimeChanging(value);
                ReportPropertyChanging("MessageReadTime");
                _MessageReadTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MessageReadTime");
                OnMessageReadTimeChanged();
            }
        }
        private global::System.DateTime _MessageReadTime;
        partial void OnMessageReadTimeChanging(global::System.DateTime value);
        partial void OnMessageReadTimeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PubSubModel", Name="Message2")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Message2 : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Message2 object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="messageID">Initial value of the MessageID property.</param>
        /// <param name="subscriptionID">Initial value of the SubscriptionID property.</param>
        /// <param name="guid">Initial value of the Guid property.</param>
        /// <param name="messagePutTime">Initial value of the MessagePutTime property.</param>
        /// <param name="messageReadTime">Initial value of the MessageReadTime property.</param>
        /// <param name="timestamp">Initial value of the Timestamp property.</param>
        /// <param name="batchNumber">Initial value of the BatchNumber property.</param>
        public static Message2 CreateMessage2(global::System.Int32 id, global::System.String name, global::System.String messageID, global::System.String subscriptionID, global::System.Guid guid, global::System.DateTime messagePutTime, global::System.DateTime messageReadTime, global::System.Byte[] timestamp, global::System.Int32 batchNumber)
        {
            Message2 message2 = new Message2();
            message2.ID = id;
            message2.Name = name;
            message2.MessageID = messageID;
            message2.SubscriptionID = subscriptionID;
            message2.Guid = guid;
            message2.MessagePutTime = messagePutTime;
            message2.MessageReadTime = messageReadTime;
            message2.Timestamp = timestamp;
            message2.BatchNumber = batchNumber;
            return message2;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                OnIDChanging(value);
                ReportPropertyChanging("ID");
                _ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID");
                OnIDChanged();
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MessageID
        {
            get
            {
                return _MessageID;
            }
            set
            {
                OnMessageIDChanging(value);
                ReportPropertyChanging("MessageID");
                _MessageID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MessageID");
                OnMessageIDChanged();
            }
        }
        private global::System.String _MessageID;
        partial void OnMessageIDChanging(global::System.String value);
        partial void OnMessageIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SubscriptionID
        {
            get
            {
                return _SubscriptionID;
            }
            set
            {
                OnSubscriptionIDChanging(value);
                ReportPropertyChanging("SubscriptionID");
                _SubscriptionID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SubscriptionID");
                OnSubscriptionIDChanged();
            }
        }
        private global::System.String _SubscriptionID;
        partial void OnSubscriptionIDChanging(global::System.String value);
        partial void OnSubscriptionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Guid
        {
            get
            {
                return _Guid;
            }
            set
            {
                if (_Guid != value)
                {
                    OnGuidChanging(value);
                    ReportPropertyChanging("Guid");
                    _Guid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Guid");
                    OnGuidChanged();
                }
            }
        }
        private global::System.Guid _Guid;
        partial void OnGuidChanging(global::System.Guid value);
        partial void OnGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime MessagePutTime
        {
            get
            {
                return _MessagePutTime;
            }
            set
            {
                OnMessagePutTimeChanging(value);
                ReportPropertyChanging("MessagePutTime");
                _MessagePutTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MessagePutTime");
                OnMessagePutTimeChanged();
            }
        }
        private global::System.DateTime _MessagePutTime;
        partial void OnMessagePutTimeChanging(global::System.DateTime value);
        partial void OnMessagePutTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime MessageReadTime
        {
            get
            {
                return _MessageReadTime;
            }
            set
            {
                OnMessageReadTimeChanging(value);
                ReportPropertyChanging("MessageReadTime");
                _MessageReadTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MessageReadTime");
                OnMessageReadTimeChanged();
            }
        }
        private global::System.DateTime _MessageReadTime;
        partial void OnMessageReadTimeChanging(global::System.DateTime value);
        partial void OnMessageReadTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Timestamp
        {
            get
            {
                return StructuralObject.GetValidValue(_Timestamp);
            }
            set
            {
                OnTimestampChanging(value);
                ReportPropertyChanging("Timestamp");
                _Timestamp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Timestamp");
                OnTimestampChanged();
            }
        }
        private global::System.Byte[] _Timestamp;
        partial void OnTimestampChanging(global::System.Byte[] value);
        partial void OnTimestampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BatchNumber
        {
            get
            {
                return _BatchNumber;
            }
            set
            {
                OnBatchNumberChanging(value);
                ReportPropertyChanging("BatchNumber");
                _BatchNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BatchNumber");
                OnBatchNumberChanged();
            }
        }
        private global::System.Int32 _BatchNumber;
        partial void OnBatchNumberChanging(global::System.Int32 value);
        partial void OnBatchNumberChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PubSubModel", Name="Message3")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Message3 : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Message3 object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="messageID">Initial value of the MessageID property.</param>
        /// <param name="subscriptionID">Initial value of the SubscriptionID property.</param>
        /// <param name="guid">Initial value of the Guid property.</param>
        /// <param name="messagePutTime">Initial value of the MessagePutTime property.</param>
        /// <param name="messageReadTime">Initial value of the MessageReadTime property.</param>
        /// <param name="timestamp">Initial value of the Timestamp property.</param>
        /// <param name="batchNumber">Initial value of the BatchNumber property.</param>
        public static Message3 CreateMessage3(global::System.Int32 id, global::System.String name, global::System.String messageID, global::System.String subscriptionID, global::System.Guid guid, global::System.DateTime messagePutTime, global::System.DateTime messageReadTime, global::System.Byte[] timestamp, global::System.Int32 batchNumber)
        {
            Message3 message3 = new Message3();
            message3.ID = id;
            message3.Name = name;
            message3.MessageID = messageID;
            message3.SubscriptionID = subscriptionID;
            message3.Guid = guid;
            message3.MessagePutTime = messagePutTime;
            message3.MessageReadTime = messageReadTime;
            message3.Timestamp = timestamp;
            message3.BatchNumber = batchNumber;
            return message3;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                OnIDChanging(value);
                ReportPropertyChanging("ID");
                _ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID");
                OnIDChanged();
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MessageID
        {
            get
            {
                return _MessageID;
            }
            set
            {
                OnMessageIDChanging(value);
                ReportPropertyChanging("MessageID");
                _MessageID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MessageID");
                OnMessageIDChanged();
            }
        }
        private global::System.String _MessageID;
        partial void OnMessageIDChanging(global::System.String value);
        partial void OnMessageIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SubscriptionID
        {
            get
            {
                return _SubscriptionID;
            }
            set
            {
                OnSubscriptionIDChanging(value);
                ReportPropertyChanging("SubscriptionID");
                _SubscriptionID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SubscriptionID");
                OnSubscriptionIDChanged();
            }
        }
        private global::System.String _SubscriptionID;
        partial void OnSubscriptionIDChanging(global::System.String value);
        partial void OnSubscriptionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Guid
        {
            get
            {
                return _Guid;
            }
            set
            {
                if (_Guid != value)
                {
                    OnGuidChanging(value);
                    ReportPropertyChanging("Guid");
                    _Guid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Guid");
                    OnGuidChanged();
                }
            }
        }
        private global::System.Guid _Guid;
        partial void OnGuidChanging(global::System.Guid value);
        partial void OnGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime MessagePutTime
        {
            get
            {
                return _MessagePutTime;
            }
            set
            {
                OnMessagePutTimeChanging(value);
                ReportPropertyChanging("MessagePutTime");
                _MessagePutTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MessagePutTime");
                OnMessagePutTimeChanged();
            }
        }
        private global::System.DateTime _MessagePutTime;
        partial void OnMessagePutTimeChanging(global::System.DateTime value);
        partial void OnMessagePutTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime MessageReadTime
        {
            get
            {
                return _MessageReadTime;
            }
            set
            {
                OnMessageReadTimeChanging(value);
                ReportPropertyChanging("MessageReadTime");
                _MessageReadTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MessageReadTime");
                OnMessageReadTimeChanged();
            }
        }
        private global::System.DateTime _MessageReadTime;
        partial void OnMessageReadTimeChanging(global::System.DateTime value);
        partial void OnMessageReadTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Timestamp
        {
            get
            {
                return StructuralObject.GetValidValue(_Timestamp);
            }
            set
            {
                OnTimestampChanging(value);
                ReportPropertyChanging("Timestamp");
                _Timestamp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Timestamp");
                OnTimestampChanged();
            }
        }
        private global::System.Byte[] _Timestamp;
        partial void OnTimestampChanging(global::System.Byte[] value);
        partial void OnTimestampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BatchNumber
        {
            get
            {
                return _BatchNumber;
            }
            set
            {
                OnBatchNumberChanging(value);
                ReportPropertyChanging("BatchNumber");
                _BatchNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BatchNumber");
                OnBatchNumberChanged();
            }
        }
        private global::System.Int32 _BatchNumber;
        partial void OnBatchNumberChanging(global::System.Int32 value);
        partial void OnBatchNumberChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PubSubModel", Name="Message4")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Message4 : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Message4 object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="messageID">Initial value of the MessageID property.</param>
        /// <param name="subscriptionID">Initial value of the SubscriptionID property.</param>
        /// <param name="guid">Initial value of the Guid property.</param>
        /// <param name="messagePutTime">Initial value of the MessagePutTime property.</param>
        /// <param name="messageReadTime">Initial value of the MessageReadTime property.</param>
        /// <param name="timestamp">Initial value of the Timestamp property.</param>
        /// <param name="batchNumber">Initial value of the BatchNumber property.</param>
        public static Message4 CreateMessage4(global::System.Int32 id, global::System.String name, global::System.String messageID, global::System.String subscriptionID, global::System.Guid guid, global::System.DateTime messagePutTime, global::System.DateTime messageReadTime, global::System.Byte[] timestamp, global::System.Int32 batchNumber)
        {
            Message4 message4 = new Message4();
            message4.ID = id;
            message4.Name = name;
            message4.MessageID = messageID;
            message4.SubscriptionID = subscriptionID;
            message4.Guid = guid;
            message4.MessagePutTime = messagePutTime;
            message4.MessageReadTime = messageReadTime;
            message4.Timestamp = timestamp;
            message4.BatchNumber = batchNumber;
            return message4;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                OnIDChanging(value);
                ReportPropertyChanging("ID");
                _ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID");
                OnIDChanged();
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MessageID
        {
            get
            {
                return _MessageID;
            }
            set
            {
                OnMessageIDChanging(value);
                ReportPropertyChanging("MessageID");
                _MessageID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MessageID");
                OnMessageIDChanged();
            }
        }
        private global::System.String _MessageID;
        partial void OnMessageIDChanging(global::System.String value);
        partial void OnMessageIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SubscriptionID
        {
            get
            {
                return _SubscriptionID;
            }
            set
            {
                OnSubscriptionIDChanging(value);
                ReportPropertyChanging("SubscriptionID");
                _SubscriptionID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SubscriptionID");
                OnSubscriptionIDChanged();
            }
        }
        private global::System.String _SubscriptionID;
        partial void OnSubscriptionIDChanging(global::System.String value);
        partial void OnSubscriptionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Guid
        {
            get
            {
                return _Guid;
            }
            set
            {
                if (_Guid != value)
                {
                    OnGuidChanging(value);
                    ReportPropertyChanging("Guid");
                    _Guid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Guid");
                    OnGuidChanged();
                }
            }
        }
        private global::System.Guid _Guid;
        partial void OnGuidChanging(global::System.Guid value);
        partial void OnGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime MessagePutTime
        {
            get
            {
                return _MessagePutTime;
            }
            set
            {
                OnMessagePutTimeChanging(value);
                ReportPropertyChanging("MessagePutTime");
                _MessagePutTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MessagePutTime");
                OnMessagePutTimeChanged();
            }
        }
        private global::System.DateTime _MessagePutTime;
        partial void OnMessagePutTimeChanging(global::System.DateTime value);
        partial void OnMessagePutTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime MessageReadTime
        {
            get
            {
                return _MessageReadTime;
            }
            set
            {
                OnMessageReadTimeChanging(value);
                ReportPropertyChanging("MessageReadTime");
                _MessageReadTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MessageReadTime");
                OnMessageReadTimeChanged();
            }
        }
        private global::System.DateTime _MessageReadTime;
        partial void OnMessageReadTimeChanging(global::System.DateTime value);
        partial void OnMessageReadTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Timestamp
        {
            get
            {
                return StructuralObject.GetValidValue(_Timestamp);
            }
            set
            {
                OnTimestampChanging(value);
                ReportPropertyChanging("Timestamp");
                _Timestamp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Timestamp");
                OnTimestampChanged();
            }
        }
        private global::System.Byte[] _Timestamp;
        partial void OnTimestampChanging(global::System.Byte[] value);
        partial void OnTimestampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BatchNumber
        {
            get
            {
                return _BatchNumber;
            }
            set
            {
                OnBatchNumberChanging(value);
                ReportPropertyChanging("BatchNumber");
                _BatchNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BatchNumber");
                OnBatchNumberChanged();
            }
        }
        private global::System.Int32 _BatchNumber;
        partial void OnBatchNumberChanging(global::System.Int32 value);
        partial void OnBatchNumberChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PubSubModel", Name="Message5")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Message5 : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Message5 object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="messageID">Initial value of the MessageID property.</param>
        /// <param name="subscriptionID">Initial value of the SubscriptionID property.</param>
        /// <param name="guid">Initial value of the Guid property.</param>
        /// <param name="messagePutTime">Initial value of the MessagePutTime property.</param>
        /// <param name="messageReadTime">Initial value of the MessageReadTime property.</param>
        /// <param name="timestamp">Initial value of the Timestamp property.</param>
        /// <param name="batchNumber">Initial value of the BatchNumber property.</param>
        public static Message5 CreateMessage5(global::System.Int32 id, global::System.String name, global::System.String messageID, global::System.String subscriptionID, global::System.Guid guid, global::System.DateTime messagePutTime, global::System.DateTime messageReadTime, global::System.Byte[] timestamp, global::System.Int32 batchNumber)
        {
            Message5 message5 = new Message5();
            message5.ID = id;
            message5.Name = name;
            message5.MessageID = messageID;
            message5.SubscriptionID = subscriptionID;
            message5.Guid = guid;
            message5.MessagePutTime = messagePutTime;
            message5.MessageReadTime = messageReadTime;
            message5.Timestamp = timestamp;
            message5.BatchNumber = batchNumber;
            return message5;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                OnIDChanging(value);
                ReportPropertyChanging("ID");
                _ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID");
                OnIDChanged();
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MessageID
        {
            get
            {
                return _MessageID;
            }
            set
            {
                OnMessageIDChanging(value);
                ReportPropertyChanging("MessageID");
                _MessageID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MessageID");
                OnMessageIDChanged();
            }
        }
        private global::System.String _MessageID;
        partial void OnMessageIDChanging(global::System.String value);
        partial void OnMessageIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SubscriptionID
        {
            get
            {
                return _SubscriptionID;
            }
            set
            {
                OnSubscriptionIDChanging(value);
                ReportPropertyChanging("SubscriptionID");
                _SubscriptionID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SubscriptionID");
                OnSubscriptionIDChanged();
            }
        }
        private global::System.String _SubscriptionID;
        partial void OnSubscriptionIDChanging(global::System.String value);
        partial void OnSubscriptionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Guid
        {
            get
            {
                return _Guid;
            }
            set
            {
                if (_Guid != value)
                {
                    OnGuidChanging(value);
                    ReportPropertyChanging("Guid");
                    _Guid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Guid");
                    OnGuidChanged();
                }
            }
        }
        private global::System.Guid _Guid;
        partial void OnGuidChanging(global::System.Guid value);
        partial void OnGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime MessagePutTime
        {
            get
            {
                return _MessagePutTime;
            }
            set
            {
                OnMessagePutTimeChanging(value);
                ReportPropertyChanging("MessagePutTime");
                _MessagePutTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MessagePutTime");
                OnMessagePutTimeChanged();
            }
        }
        private global::System.DateTime _MessagePutTime;
        partial void OnMessagePutTimeChanging(global::System.DateTime value);
        partial void OnMessagePutTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime MessageReadTime
        {
            get
            {
                return _MessageReadTime;
            }
            set
            {
                OnMessageReadTimeChanging(value);
                ReportPropertyChanging("MessageReadTime");
                _MessageReadTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MessageReadTime");
                OnMessageReadTimeChanged();
            }
        }
        private global::System.DateTime _MessageReadTime;
        partial void OnMessageReadTimeChanging(global::System.DateTime value);
        partial void OnMessageReadTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Timestamp
        {
            get
            {
                return StructuralObject.GetValidValue(_Timestamp);
            }
            set
            {
                OnTimestampChanging(value);
                ReportPropertyChanging("Timestamp");
                _Timestamp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Timestamp");
                OnTimestampChanged();
            }
        }
        private global::System.Byte[] _Timestamp;
        partial void OnTimestampChanging(global::System.Byte[] value);
        partial void OnTimestampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BatchNumber
        {
            get
            {
                return _BatchNumber;
            }
            set
            {
                OnBatchNumberChanging(value);
                ReportPropertyChanging("BatchNumber");
                _BatchNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BatchNumber");
                OnBatchNumberChanged();
            }
        }
        private global::System.Int32 _BatchNumber;
        partial void OnBatchNumberChanging(global::System.Int32 value);
        partial void OnBatchNumberChanged();

        #endregion
    
    }

    #endregion
    
}
